#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Apr 26 16:02:41 2022
#

import wx

import json
import os
from pathlib import Path

from remoteIR import remote #read data from IR receiver

import logging

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):



    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        #self.SetSize((444, 525))

        width=450
        hight=700
        self.SetSizeHints(width,hight,width,hight)
        self.SetTitle("Wizard to get the IR codes for PYERIR.")

        self.receiverIR=remote()


        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Press the button GET, then press the button on the remote control.")
        sizer_1.Add(label_1, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_labels = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_labels, 2, wx.ALL | wx.EXPAND, 3)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "- BUTTONS -", style=wx.ALIGN_CENTER_HORIZONTAL | wx.ST_NO_AUTORESIZE)
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_labels.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "UP", style=wx.ALIGN_LEFT)
        label_7.SetMinSize((140, 35))
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_7, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "DOWN")
        label_8.SetMinSize((140, 30))
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "LEFT")
        label_9.SetMinSize((140, 30))
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "RIGHT")
        label_10.SetMinSize((140, 30))
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "OK")
        label_11.SetMinSize((140, 30))
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_11, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "*")
        label_12.SetMinSize((140, 30))
        sizer_labels.Add(label_12, 0, 0, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "#", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_13.SetMinSize((140, 23))
        sizer_labels.Add(label_13, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "0")
        label_14.SetMinSize((140, 30))
        sizer_labels.Add(label_14, 0, 0, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "1")
        label_15.SetMinSize((140, 30))
        sizer_labels.Add(label_15, 0, 0, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "2")
        label_16.SetMinSize((140, 30))
        sizer_labels.Add(label_16, 0, 0, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "3")
        label_17.SetMinSize((140, 30))
        sizer_labels.Add(label_17, 0, 0, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "4")
        label_18.SetMinSize((140, 30))
        sizer_labels.Add(label_18, 0, 0, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "5")
        label_19.SetMinSize((140, 30))
        sizer_labels.Add(label_19, 0, 0, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "6")
        label_20.SetMinSize((140, 30))
        sizer_labels.Add(label_20, 0, 0, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "7")
        label_21.SetMinSize((140, 30))
        sizer_labels.Add(label_21, 0, 0, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "8")
        label_22.SetMinSize((140, 30))
        sizer_labels.Add(label_22, 0, 0, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "9")
        label_23.SetMinSize((140, 30))
        sizer_labels.Add(label_23, 0, 0, 0)

        sizer_text_box = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_text_box, 3, wx.ALL | wx.EXPAND, 1)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "- IR_CODE -")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_text_box.Add(label_5, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        self.text_ctrl_up = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_up.SetMinSize((145, 38))
        sizer_text_box.Add(self.text_ctrl_up, 0, wx.EXPAND, 0)
        self.text_ctrl_up.SetValue(remote.IRcodes["up"])

        self.text_ctrl_down = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.text_ctrl_down.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_down, 0, wx.EXPAND, 0)
        self.text_ctrl_down.SetValue(remote.IRcodes["down"])

        self.text_ctrl_left = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_left.SetMinSize((140, 30))
        sizer_text_box.Add(self.text_ctrl_left, 0, wx.EXPAND, 0)
        self.text_ctrl_left.SetValue(remote.IRcodes["left"])

        self.text_ctrl_right = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_right.SetMinSize((140, 31))
        sizer_text_box.Add(self.text_ctrl_right, 0, wx.EXPAND, 0)
        self.text_ctrl_right.SetValue(remote.IRcodes["right"])

        self.text_ctrl_ok = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_ok.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_ok, 0, wx.EXPAND, 0)
        self.text_ctrl_ok.SetValue(remote.IRcodes["ok"])

        self.text_ctrl_asterisk = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_asterisk.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_asterisk, 0, wx.EXPAND, 0)
        self.text_ctrl_asterisk.SetValue(remote.IRcodes["asterisk"])

        self.text_ctrl_hash = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_hash.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_hash, 0, wx.EXPAND, 0)
        self.text_ctrl_hash.SetValue(remote.IRcodes["hash"])

        self.text_ctrl_0 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_0.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_0, 0, wx.EXPAND, 0)
        self.text_ctrl_0.SetValue(remote.IRcodes["zero"])

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_1.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        self.text_ctrl_1.SetValue(remote.IRcodes["one"])

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_2.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        self.text_ctrl_2.SetValue(remote.IRcodes["two"])

        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_3.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_3, 0, wx.EXPAND, 0) 
        self.text_ctrl_3.SetValue(remote.IRcodes["three"])

        self.text_ctrl_4 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_4.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        self.text_ctrl_4.SetValue(remote.IRcodes["four"])

        self.text_ctrl_5 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_5.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_5, 0, wx.EXPAND, 0)
        self.text_ctrl_5.SetValue(remote.IRcodes["five"])

        self.text_ctrl_6 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_6.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_6, 0, wx.EXPAND, 0)
        self.text_ctrl_6.SetValue(remote.IRcodes["six"])

        self.text_ctrl_7 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_7.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_7, 0, wx.EXPAND, 0)
        self.text_ctrl_7.SetValue(remote.IRcodes["seven"])

        self.text_ctrl_8 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_8.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_8, 0, wx.EXPAND, 0)
        self.text_ctrl_8.SetValue(remote.IRcodes["eight"])

        self.text_ctrl_9 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_9.SetMinSize((140, 32))
        sizer_text_box.Add(self.text_ctrl_9, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        self.text_ctrl_9.SetValue(remote.IRcodes["nine"])

        sizer_buttons = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_buttons, 0, wx.ALL | wx.EXPAND, 1)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "---------")
        label_6.SetSize(1,5)
        sizer_buttons.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_up = wx.Button(self.panel_1, wx.ID_ANY, "Get_up")
        sizer_buttons.Add(self.button_up, 0, wx.EXPAND, 0)

        self.button_down = wx.Button(self.panel_1, wx.ID_ANY, "Get_down")
        sizer_buttons.Add(self.button_down, 0, wx.EXPAND, 0)

        self.button_left = wx.Button(self.panel_1, wx.ID_ANY, "Get_left")
        sizer_buttons.Add(self.button_left, 0, wx.EXPAND, 0)

        self.button_right = wx.Button(self.panel_1, wx.ID_ANY, "Get_right")
        sizer_buttons.Add(self.button_right, 0, wx.EXPAND, 0)

        self.button_OK = wx.Button(self.panel_1, wx.ID_ANY, "Get_ok")
        sizer_buttons.Add(self.button_OK, 0, wx.EXPAND, 0)

        self.button_ASTERISK = wx.Button(self.panel_1, wx.ID_ANY, "Get_*")
        sizer_buttons.Add(self.button_ASTERISK, 0, wx.EXPAND, 0)

        self.button_hash = wx.Button(self.panel_1, wx.ID_ANY, "Get_#")
        sizer_buttons.Add(self.button_hash, 0, wx.EXPAND, 0)

        self.button_0 = wx.Button(self.panel_1, wx.ID_ANY, "Get_0")
        sizer_buttons.Add(self.button_0, 0, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Get_1")
        sizer_buttons.Add(self.button_1, 0, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Get_2")
        sizer_buttons.Add(self.button_2, 0, wx.EXPAND, 0)

        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "Get_3")
        sizer_buttons.Add(self.button_3, 0, wx.EXPAND, 0)

        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, "Get_4")
        sizer_buttons.Add(self.button_4, 0, wx.EXPAND, 0)

        self.button_5 = wx.Button(self.panel_1, wx.ID_ANY, "Get_5")
        sizer_buttons.Add(self.button_5, 0, wx.EXPAND, 0)

        self.button_6 = wx.Button(self.panel_1, wx.ID_ANY, "Get_6")
        sizer_buttons.Add(self.button_6, 0, wx.EXPAND, 0)

        self.button_7 = wx.Button(self.panel_1, wx.ID_ANY, "Get_7")
        sizer_buttons.Add(self.button_7, 0, wx.EXPAND, 0)

        self.button_8 = wx.Button(self.panel_1, wx.ID_ANY, "Get_8")
        sizer_buttons.Add(self.button_8, 0, wx.EXPAND, 0)

        self.button_9 = wx.Button(self.panel_1, wx.ID_ANY, "Get_9")
        sizer_buttons.Add(self.button_9, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Free to use!")
        sizer_1.Add(label_2, 0, 0, 0)

        self.btnSaveIRcodes = wx.Button(self.panel_1, wx.ID_ANY, "Save IRcodes", style=wx.BU_AUTODRAW | wx.BU_LEFT | wx.BU_RIGHT)
        sizer_1.Add(self.btnSaveIRcodes, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_BUTTON, self.Get_up, self.button_up)
        self.Bind(wx.EVT_BUTTON, self.Get_down, self.button_down)
        self.Bind(wx.EVT_BUTTON, self.Get_left, self.button_left)
        self.Bind(wx.EVT_BUTTON, self.Get_right, self.button_right)
        self.Bind(wx.EVT_BUTTON, self.Get_ok, self.button_OK)
        self.Bind(wx.EVT_BUTTON, self.Get_Asterisk, self.button_ASTERISK)
        self.Bind(wx.EVT_BUTTON, self.Get_hash, self.button_hash)
        self.Bind(wx.EVT_BUTTON, self.Get_0, self.button_0)
        self.Bind(wx.EVT_BUTTON, self.Get_1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.Get_2, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.Get_3, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.Get_4, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.Get_5, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.Get_6, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.Get_7, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.Get_8, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.Get_9, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.Save_json, self.btnSaveIRcodes)
        # end wxGlade

    def Get_up(self, event):  
        self.ShowMessage("Acept and press button for up key on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["up"]=codigo
        self.text_ctrl_up.SetValue(remote.IRcodes["up"])
        self.text_ctrl_up.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_down(self, event):  
        self.ShowMessage("Acept and press button for down key on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["down"]=codigo
        self.text_ctrl_down.SetValue(remote.IRcodes["down"])
        self.text_ctrl_down.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_left(self, event):  
        self.ShowMessage("Acept and press button for left key on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["left"]=codigo
        self.text_ctrl_left.SetValue(remote.IRcodes["left"])
        self.text_ctrl_left.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_right(self, event):  
        self.ShowMessage("Acept and press button for right key on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["right"]=codigo
        self.text_ctrl_right.SetValue(remote.IRcodes["right"])
        self.text_ctrl_right.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_ok(self, event):  
        self.ShowMessage("Acept and press button for ok on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["ok"]=codigo
        self.text_ctrl_ok.SetValue(remote.IRcodes["ok"])
        self.text_ctrl_ok.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_Asterisk(self, event):  
        self.ShowMessage("Acept and press button for * on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["asterisk"]=codigo
        self.text_ctrl_asterisk.SetValue(remote.IRcodes["asterisk"])
        self.text_ctrl_asterisk.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_hash(self, event):  
        self.ShowMessage("Acept and press button for # on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["hash"]=codigo
        self.text_ctrl_hash.SetValue(remote.IRcodes["hash"])
        self.text_ctrl_hash.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_0(self, event):  
        self.ShowMessage("Acept and press button for number 0 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["zero"]=codigo
        self.text_ctrl_0.SetValue(remote.IRcodes["zero"])
        self.text_ctrl_0.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_1(self, event):  
        self.ShowMessage("Acept and press button for number 1 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["one"]=codigo
        self.text_ctrl_1.SetValue(remote.IRcodes["one"])
        self.text_ctrl_1.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_2(self, event):  
        self.ShowMessage("Acept and press button for number 2 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["two"]=codigo
        self.text_ctrl_2.SetValue(remote.IRcodes["two"])
        self.text_ctrl_2.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_3(self, event):  
        self.ShowMessage("Acept and press button for number 3 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["three"]=codigo
        self.text_ctrl_3.SetValue(remote.IRcodes["three"])
        self.text_ctrl_3.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_4(self, event):  
        self.ShowMessage("Acept and press button for number 4 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["four"]=codigo
        self.text_ctrl_4.SetValue(remote.IRcodes["four"])
        self.text_ctrl_4.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_5(self, event):  
        self.ShowMessage("Acept and press button for number 5 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["five"]=codigo
        self.text_ctrl_5.SetValue(remote.IRcodes["five"])
        self.text_ctrl_5.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_6(self, event):  
        self.ShowMessage("Acept and press button for number 6 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["six"]=codigo
        self.text_ctrl_6.SetValue(remote.IRcodes["six"])
        self.text_ctrl_6.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_7(self, event):  
        self.ShowMessage("Acept and press button for number 7 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["seven"]=codigo
        self.text_ctrl_7.SetValue(remote.IRcodes["seven"])
        self.text_ctrl_7.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_8(self, event):  
        self.ShowMessage("Acept and press button for number 8 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["eight"]=codigo
        self.text_ctrl_8.SetValue(remote.IRcodes["eight"])
        self.text_ctrl_8.SetBackgroundColour(wx.Colour(255,255,0))
        logging.debug("IR code: "+str(codigo))

    def Get_9(self, event):  
        self.ShowMessage("Acept and press button for number 9 on remote control!")
        codigo=self.receiverIR.Getcode()
        remote.IRcodes["nine"]=codigo
        self.text_ctrl_9.SetValue(remote.IRcodes["nine"])
        self.text_ctrl_9.SetBackgroundColour(wx.Colour(255,255,0))
        
        logging.debug("IR code: "+str(codigo))

    def Save_json(self, event):  
        jsonfile={}
        for keyIRcode in remote.IRcodes:
            #create json
            jsonfile[keyIRcode]=str(remote.IRcodes[keyIRcode])
            print(keyIRcode+" = "+str(remote.IRcodes[keyIRcode]))
        jsonString = json.dumps(jsonfile)
        json_file=os.path.join(Path( __file__ ).parent.absolute(),"remoteIR.json") 
        jsonFile = open(json_file, "w")
        jsonFile.write(jsonString)
        jsonFile.close()
        self.ShowMessage("IR codes saved in the file: remoteIR.json")

    def ShowMessage(self,texto):
            wx.MessageBox(texto, 'Info',wx.OK | wx.ICON_INFORMATION)
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

#
if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
