#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Apr 26 16:02:41 2022
#

import wx
#from remoteIR import remote #read data from IR receiver
import json
import os
from pathlib import Path

from remoteIR import remote #read data from IR receiver

import logging

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
#dictionary of remote IR codes
    remoteIR={
        "ok":   b'\x00\xff\x1c\xe3',
        "left": b'\x00\xff\x08\xf7',
        "right": b'\x00\xffZ\xa5',
        "up":   b'\x00\xff\x18\xe7',
        "down": b'\x00\xffR\xad',
        "one":  b'\x00\xffE\xba',
        "two":  b'\x00\xffF\xb9',
        "three": b'\x00\xffG\xb8',
        "four": b'\x00\xffD\xbb',
        "five": b'\x00\xff@\xbf',
        "six":  b'\x00\xffC\xbc',
        "seven": b'\x00\xff\x07\xf8',
        "eight": b'\x00\xff\x15\xea',
        "nine": b'\x00\xff\t\xf6',
        "zero": b'\x00\xff\x19\xe6',
        "asterisk": b'\x00\xff\x16\xe9',
        "hash": b'\x00\xff\r\xf2'
    }


    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        #self.SetSize((444, 525))
        width=400
        hight=500
        self.SetSizeHints(width,hight,width,hight)
        self.SetTitle("Wizard to get the IR codes for PYERIR.")
        
        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, "Press the button GET, then press the button on the remote control.")
        sizer_1.Add(label_1, 0, 0, 0)

        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_labels = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_labels, 2, wx.ALL | wx.EXPAND, 3)

        label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, "- BUTTONS -", style=wx.ALIGN_CENTER_HORIZONTAL | wx.ST_NO_AUTORESIZE)
        label_4.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_labels.Add(label_4, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, "UP", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_7.SetMinSize((140, 23))
        label_7.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_7, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_8 = wx.StaticText(self.panel_1, wx.ID_ANY, "DOWN", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_8.SetMinSize((140, 23))
        label_8.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_9 = wx.StaticText(self.panel_1, wx.ID_ANY, "LEFT", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_9.SetMinSize((140, 23))
        label_9.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_9, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_10 = wx.StaticText(self.panel_1, wx.ID_ANY, "RIGHT", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_10.SetMinSize((140, 23))
        label_10.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_11 = wx.StaticText(self.panel_1, wx.ID_ANY, "OK", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_11.SetMinSize((140, 23))
        label_11.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_labels.Add(label_11, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_12 = wx.StaticText(self.panel_1, wx.ID_ANY, "*", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_12.SetMinSize((140, 23))
        sizer_labels.Add(label_12, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_13 = wx.StaticText(self.panel_1, wx.ID_ANY, "#", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_13.SetMinSize((140, 23))
        sizer_labels.Add(label_13, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_14 = wx.StaticText(self.panel_1, wx.ID_ANY, "0", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_14.SetMinSize((140, 23))
        sizer_labels.Add(label_14, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_15 = wx.StaticText(self.panel_1, wx.ID_ANY, "1", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_15.SetMinSize((140, 23))
        sizer_labels.Add(label_15, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_16 = wx.StaticText(self.panel_1, wx.ID_ANY, "2", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_16.SetMinSize((140, 23))
        sizer_labels.Add(label_16, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_17 = wx.StaticText(self.panel_1, wx.ID_ANY, "3", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_17.SetMinSize((140, 23))
        sizer_labels.Add(label_17, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_18 = wx.StaticText(self.panel_1, wx.ID_ANY, "4", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_18.SetMinSize((140, 23))
        sizer_labels.Add(label_18, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_19 = wx.StaticText(self.panel_1, wx.ID_ANY, "5", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_19.SetMinSize((140, 23))
        sizer_labels.Add(label_19, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.SHAPED, 0)

        label_20 = wx.StaticText(self.panel_1, wx.ID_ANY, "6", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_20.SetMinSize((140, 23))
        sizer_labels.Add(label_20, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_21 = wx.StaticText(self.panel_1, wx.ID_ANY, "7", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_21.SetMinSize((140, 23))
        sizer_labels.Add(label_21, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_22 = wx.StaticText(self.panel_1, wx.ID_ANY, "8", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_22.SetMinSize((140, 23))
        sizer_labels.Add(label_22, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        label_23 = wx.StaticText(self.panel_1, wx.ID_ANY, "9", style=wx.ALIGN_CENTER_HORIZONTAL)
        label_23.SetMinSize((140, 23))
        sizer_labels.Add(label_23, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        sizer_text_box = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_text_box, 3, wx.ALL | wx.EXPAND, 1)

        label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, "- IR_CODE -")
        label_5.SetFont(wx.Font(10, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_BOLD, 0, ""))
        sizer_text_box.Add(label_5, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALL, 0)

        self.text_ctrl_up = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        self.text_ctrl_up.SetMinSize((140, 23))
        sizer_text_box.Add(self.text_ctrl_up, 0, wx.EXPAND, 0)
        self.text_ctrl_up.SetLabelText(str(self.remoteIR["up"]))

        self.text_ctrl_down = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_down, 0, wx.EXPAND, 0)
        self.text_ctrl_down.SetLabelText(str(self.remoteIR["down"]))

        self.text_ctrl_left = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_left, 0, wx.EXPAND, 0)
        self.text_ctrl_left.SetLabelText(str(self.remoteIR["left"]))

        self.text_ctrl_right = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_right, 0, wx.EXPAND, 0)
        self.text_ctrl_right.SetLabelText(str(self.remoteIR["right"]))

        self.text_ctrl_ok = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_ok, 0, wx.EXPAND, 0)
        self.text_ctrl_ok.SetLabelText(str(self.remoteIR["ok"]))

        self.text_ctrl_asterisk = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_asterisk, 0, wx.EXPAND, 0)
        self.text_ctrl_asterisk.SetLabelText(str(self.remoteIR["asterisk"]))

        self.text_ctrl_hash = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_hash, 0, wx.EXPAND, 0)
        self.text_ctrl_hash.SetLabelText(str(self.remoteIR["hash"]))

        self.text_ctrl_0 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_0, 0, wx.EXPAND, 0)
        self.text_ctrl_0.SetLabelText(str(self.remoteIR["zero"]))

        self.text_ctrl_1 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)
        self.text_ctrl_1.SetLabelText(str(self.remoteIR["one"]))

        self.text_ctrl_2 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)
        self.text_ctrl_2.SetLabelText(str(self.remoteIR["two"]))

        self.text_ctrl_3 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_3, 0, wx.EXPAND, 0)
        self.text_ctrl_3.SetLabelText(str(self.remoteIR["three"]))

        self.text_ctrl_4 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)
        self.text_ctrl_4.SetLabelText(str(self.remoteIR["four"]))

        self.text_ctrl_5 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_5, 0, wx.EXPAND, 0)
        self.text_ctrl_5.SetLabelText(str(self.remoteIR["five"]))

        self.text_ctrl_6 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_6, 0, wx.EXPAND, 0)
        self.text_ctrl_6.SetLabelText(str(self.remoteIR["six"]))

        self.text_ctrl_7 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_7, 0, wx.EXPAND, 0)
        self.text_ctrl_7.SetLabelText(str(self.remoteIR["seven"]))

        self.text_ctrl_8 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_8, 0, wx.EXPAND, 0)
        self.text_ctrl_8.SetLabelText(str(self.remoteIR["eight"]))

        self.text_ctrl_9 = wx.TextCtrl(self.panel_1, wx.ID_ANY, "", style=wx.TE_READONLY)
        sizer_text_box.Add(self.text_ctrl_9, 0, wx.EXPAND | wx.FIXED_MINSIZE, 0)
        self.text_ctrl_9.SetLabelText(str(self.remoteIR["nine"]))

        sizer_buttons = wx.BoxSizer(wx.VERTICAL)
        sizer_2.Add(sizer_buttons, 0, wx.ALL | wx.EXPAND, 1)

        label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, "---------")
        sizer_buttons.Add(label_6, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.button_up = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        self.button_up.SetMinSize((75, 23))
        sizer_buttons.Add(self.button_up, 0, wx.EXPAND, 0)

        self.button_down = wx.Button(self.panel_1, wx.ID_ANY, "Get\n")
        self.button_down.SetMinSize((75, 23))
        sizer_buttons.Add(self.button_down, 0, wx.EXPAND, 0)

        self.button_left = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_left, 0, wx.EXPAND, 0)

        self.button_right = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_right, 0, wx.EXPAND, 0)

        self.button_OK = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_OK, 0, wx.EXPAND, 0)

        self.button_ASTERISK = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_ASTERISK, 0, wx.EXPAND, 0)

        self.button_hash = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_hash, 0, wx.EXPAND, 0)

        self.button_0 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_0, 0, wx.EXPAND, 0)

        self.button_1 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_1, 0, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_2, 0, wx.EXPAND, 0)

        self.button_3 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_3, 0, wx.EXPAND, 0)

        self.button_4 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_4, 0, wx.EXPAND, 0)

        self.button_5 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_5, 0, wx.EXPAND, 0)

        self.button_6 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_6, 0, wx.EXPAND, 0)

        self.button_7 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_7, 0, wx.EXPAND, 0)

        self.button_8 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_8, 0, wx.EXPAND, 0)

        self.button_9 = wx.Button(self.panel_1, wx.ID_ANY, "Get")
        sizer_buttons.Add(self.button_9, 0, 0, 0)

        label_2 = wx.StaticText(self.panel_1, wx.ID_ANY, "Free to use!")
        sizer_1.Add(label_2, 0, 0, 0)

        self.btnSaveIRcodes = wx.Button(self.panel_1, wx.ID_ANY, "Save IRcodes", style=wx.BU_AUTODRAW | wx.BU_LEFT | wx.BU_RIGHT)
        sizer_1.Add(self.btnSaveIRcodes, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        self.Centre()

        self.Bind(wx.EVT_BUTTON, self.Get_up, self.button_up)
        self.Bind(wx.EVT_BUTTON, self.Get_down, self.button_down)
        self.Bind(wx.EVT_BUTTON, self.Get_left, self.button_left)
        self.Bind(wx.EVT_BUTTON, self.Get_right, self.button_right)
        self.Bind(wx.EVT_BUTTON, self.Get_ok, self.button_OK)
        self.Bind(wx.EVT_BUTTON, self.Get_Asterisk, self.button_ASTERISK)
        self.Bind(wx.EVT_BUTTON, self.Get_hash, self.button_hash)
        self.Bind(wx.EVT_BUTTON, self.Get_0, self.button_0)
        self.Bind(wx.EVT_BUTTON, self.Get_1, self.button_1)
        self.Bind(wx.EVT_BUTTON, self.Get_2, self.button_2)
        self.Bind(wx.EVT_BUTTON, self.Get_3, self.button_3)
        self.Bind(wx.EVT_BUTTON, self.Get_4, self.button_4)
        self.Bind(wx.EVT_BUTTON, self.Get_5, self.button_5)
        self.Bind(wx.EVT_BUTTON, self.Get_6, self.button_6)
        self.Bind(wx.EVT_BUTTON, self.Get_7, self.button_7)
        self.Bind(wx.EVT_BUTTON, self.Get_8, self.button_8)
        self.Bind(wx.EVT_BUTTON, self.Get_9, self.button_9)
        self.Bind(wx.EVT_BUTTON, self.Save_json, self.btnSaveIRcodes)
        # end wxGlade

    def Get_up(self, event):  
        print("Event handler 'Get_up' not implemented!")
        event.Skip()

    def Get_down(self, event):  
        print("Event handler 'Get_down' not implemented!")
        event.Skip()

    def Get_left(self, event):  
        print("Event handler 'Get_left' not implemented!")
        event.Skip()

    def Get_right(self, event):  
        print("Event handler 'Get_right' not implemented!")
        event.Skip()

    def Get_ok(self, event):  
        print("Event handler 'Get_ok' not implemented!")
        event.Skip()

    def Get_Asterisk(self, event):  
        print("Event handler 'Get_Asterisk' not implemented!")
        event.Skip()

    def Get_hash(self, event):  
        print("Event handler 'Get_hash' not implemented!")
        event.Skip()

    def Get_0(self, event):  
        print("Event handler 'Get_0' not implemented!")
        event.Skip()

    def Get_1(self, event):  
        print("Event handler 'Get_1' not implemented!")
        event.Skip()

    def Get_2(self, event):  
        print("Event handler 'Get_2' not implemented!")
        event.Skip()

    def Get_3(self, event):  
        print("Event handler 'Get_3' not implemented!")
        event.Skip()

    def Get_4(self, event):  
        self.ShowMessage("Acept and press button for number 4 on remote control!")
        codigo=self.receiverIR.Getcode()
        self.text_ctrl_4.SetLabelText(codigo)
        logging.debug("IR code: "+str(codigo))

    def Get_5(self, event):  
        print("Event handler 'Get_5' not implemented!")
        event.Skip()

    def Get_6(self, event):  
        print("Event handler 'Get_6' not implemented!")
        event.Skip()

    def Get_7(self, event):  
        print("Event handler 'Get_7' not implemented!")
        event.Skip()

    def Get_8(self, event):  
        print("Event handler 'Get_8' not implemented!")
        event.Skip()

    def Get_9(self, event):  
        print("Event handler 'Get_9' not implemented!")
        event.Skip()

    def Save_json(self, event):  
        jsonfile={}
        for keyIRcode in self.remoteIR:
            #create json
            jsonfile[keyIRcode]=str(self.remoteIR[keyIRcode])
            print(keyIRcode+" - "+str(self.remoteIR[keyIRcode]))
        jsonString = json.dumps(jsonfile)
        json_file=os.path.join(Path( __file__ ).parent.absolute(),"remoteIR.json") 
        jsonFile = open(json_file, "w")
        jsonFile.write(jsonString)
        jsonFile.close()
        self.ShowMessage("IR codes saved in the file: remoteIR.json")

    def ShowMessage(self,texto):
            wx.MessageBox(texto, 'Info',wx.OK | wx.ICON_INFORMATION)
# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

#
if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
